### PR TITLE
Add Efinity tool support (Efinix)

### PR DESCRIPTION
**Pull request by sebinho**
This is a first attempt to add support for Efinix Efinity toolchain.
I have successfully used this implementation with Edalize and FuseSoc to build projects.

To go past the synthesis stage, it is necessary to provide an ISF file (constraint file created with the tool to assign pins, etc)

This implementation might not be the cleanest approach, but it serves its purpose of opening up support for Efinix tools.

### CODE REVIEW

**Comment by sebinho** [comment]
Sorry if my code is not the cleanest, I am more of a hardware guy :-). But it did the trick for me and I am pretty much using this on a daily basis

**Comment by olofk** [comment]
The code looks mostly fine. It's more that Edalize is undergoing a larger change where we are slowly moving all the old backends to the new API, so I want to have all new code using the new API directly. The whole thing is not very well documented unfortunately, but let me work on this based on your code and I'll ping you when I have something you can try

**Comment by sebinho** [comment]
Great thanks a lot!

**Comment by olofk** [comment]
FYI, I just tried your backend and I could build the SERV reference platform perfectly fine with it. Now I just need to figure out where I put my Xyloni board so that I can actually try it too :)

**Comment by sebinho** [comment]
Great news. On my side I have been using Ti180 devkit

**Comment by ThomasHornschuh** [comment]
@sebinho: I'm also intersted in it. Which version of the Efinix software did you use for testing it?

**Comment by sebinho** [comment]
The latest version, so I suppose 2023.1.150

**Comment by olofk** [comment]
Is there a reference of the isf format somewhere? I'm trying to create a pin constraint file. Found an example XML file for my board and I believe I can export that to an isf but the Interface designer tool crashes when I try to open it

**Comment by sebinho** [comment]
Here is an example I have, rename from `*.zip` to `*.isf`

[Ti180_mipi_io.zip](https://github.com/olofk/edalize/files/12832034/Ti180_mipi_io.zip)

**Comment by sebinho** [comment]
I don't think there is a template and it is not trivial to automate the creation of ISF files. I typically do it using the interface designer, luckily it does not crash for me (Linux Ubuntu)

**Comment by olofk** [comment]
Thanks. I'll reboot into Ubuntu and try again tomorrow. I can't make sense of the pin namings so I probably need to go through the interface designer to begin with.

**Comment by olofk** [comment]
Yes! I managed to get SERV running on my Xyloni board now using Edalize with the Efinity backend. Hopefully I can get things ported to the new API early next week.

**Comment by sebinho** [comment]
Great news! Sorry I did not port it to the new API. There was not much documentation on it so I did stick to the old approach as I needed something running in a short timeframe. 
thanks 🙏

**Comment by olofk** [comment]
Just a quick update. I got it ported to the new API now. Will need some cleaning up but I'll push it on a branch somewhere so that you can have a look. There are also some windows/cygwin-specific code paths that I'm not able to test myself so it would be great to know if I messed those up.

**Comment by sebinho** [comment]
Awesome update. When you have the branch ready, let me know and I will test is asap. I should be able to test this tomorrow or the day after if it’s ready

**Comment by olofk** [comment]
@sebinho Check out the noefx branch https://github.com/olofk/edalize/tree/noefx

A few notes. In your backend, you checked the file endings. Edalize likes to use explicit file types, so you will need to set `file_type : ISF` to your ISF files for this to work. Also, I haven't created a dedicated flow class for this yet, but it works fine to use the generic flow in the meantime. You can do this by setting the following keys in your target (flow overrides default_tool, fyi).
```yaml
targets:
  yourtarget:
    flow: generic
    flow_options:
      tool: efinity
      family: Trion
      part: T8F81
      timing: C2
```

I also added a Xyloni branch to the SERV repo (https://github.com/olofk/serv/tree/xyloni) so that you can run `fusesoc run --target=xyloni servant` in case you have a Xyloni board, or just want to look at my example.

**Comment by olofk** [comment]
Also, some benefits of using the flow API
* Proper dependency tracking of files so that things only get rebuilt when needed
* Automatic support for the EDALIZE_LAUNCHER variable so that you can define launchers (e.g. to seamlessly run tools in docker containers (see el_docker for that)
* Define frontends. E.g. if your eda tool has problems grasping some SV construct, you can set `frontends : [sv2v]` to filter your design through sv2v before passing it on to the tool. Same goes for GHDL, and you can use both at the same time.
* Define tags in addition to file types, so that you can e.g. tell that a TCL script is meant for a specific tool in a tool flow and that the other tools should just ignore it.

Just a few things to point out why it's worth the hassle of going with the new API :)

**Comment by olofk** [comment]
Ah! Sorry about that. I forgot to add the two new files to setup.py. Hopefully fixed with a new commit now

**Comment by sebinho** [comment]
I just tested your new commit. It works perfectly with both your SERV project and one of my test projects.
Great! Let me know when you plan to merge this.

Thanks for the help

**Comment by olofk** [comment]
I made a new branch now here https://github.com/olofk/edalize/tree/efx2 where I basically replaced your original commit with the port to the new flow API. Since you did the heavy lifting I wanted to make sure you get the credit. Let me know if you're fine with this and I'll merge it right away.

**Comment by sebinho** [comment]
It looks good to me
Thanks for letting me be part of the project credentials ;-)

So I suppose that once this is merged, I will have to continue using the generic flow until further notice?

**Comment by olofk** [comment]
Great!

And yes. Forgot about that part. Hope to put together the flow class tonight or tomorrow. I'll ping you about that

**Comment by olofk** [comment]
Alright @sebinho . There's now a flow class also, so you can simplify your target to 

```yaml
targets:
  yourtarget:
    flow: efinity
    flow_options:
      family: Trion
      part: T8F81
      timing: C2
```

Thank you for your contributions and feel free to close when you have checked that it works correctly.

**Comment by sebinho** [comment]
Hi Olof,

I did notice something yesterday and wanted to get your opinion on this. When using efinity flow, if I use the `default` target together with an `ISF` file for constraints, the `ISF` file is not included in the project. I have to rename my target into something else than `default` and then it is properly included.
This is not a problem per se, just something I did not know/expect.

Thanks for your help!

**Comment by olofk** [comment]
Sorry @sebinho. Missed your comment. That sounds super weird. I did a quick test with corescore where I just renamed the xyloni target to default, and I could not reproduce the issue. I wonder if there's something else we're seeing here

**Pull request closed without merging**
