### PR TITLE
write_filelist: adding new filelist backend.

### PR DESCRIPTION
**Pull request by sjalloq**
This is a first pass at the filelist backend.  Still looking for feedback from the original discussion but thought a PR might kick start that.  No test updates yet.

See https://github.com/olofk/edalize/issues/25 for original discussion.

### CODE REVIEW

**Comment by olofk** [comment]
As you know, I had another preferred way of doing this, but I have also come to realize that it's much better to get this in than waiting for another fictive solution that doesn't exist yet. I would appreciate adding tests though, but this looks fine and I understand you are using this yourself successfully, so let's pull it in as is.

Thank you for your contributions.

**Comment by shareefj** [comment]
OK, thanks.  I can take a look at adding tests and if anyone else has any feedback on its usage then I can rework this.  This has diverged somewhat from our own branch so I'll double check it still all hangs together correctly.

On the topic of your preferred way, happy to help out in any spare cycles I get.  I remember you'd replied to a comment somewhere on how you saw it working, but if you put that in a branch and/or a new ticket then perhaps we can work on it in the background.

**Comment by shareefj** [comment]
Ah yes, it's not going to work as is.  @olofk - you didn't want to push the other half of this request which was to add `top_core` to the Fusesoc EDAM arguments.  This works for us as we're still using our own branch: https://github.com/idex-biometrics/fusesoc/commit/05695284cf5e26128dcfcb53951eef37b670190f

**Comment by davidp135** [comment]
Great, thanks Il give it a try on my own branch. @olofk is this something that will go into the main branch of Fusesoc at some point?

**Comment by shareefj** [comment]
@davidp135  Just for some background.  Olof had a reservation that adding a new key would somehow break backwards compatibility but I couldn't see it at the time and the conversation went cold.  So this proposal was shelved and we were going to look at a script that could post process the EDAM YAML or something.  I forget the details.  There's a ticket with a short discussion somewhere.

I think this PR was merged following me showing someone else an example but we both forgot that there was a corresponding Fusesoc PR that he didn't want to put in.

Given the fix to Fusesoc is a single line you should be able to patch that on top of latest.  I might even merge olofk/fusesoc/master into my branch at some point.  But we probably need to revisit this sooner if people think it might be useful.

**Comment by davidp135** [comment]
Great thanks @shareefj  I have applied the patch and am now getting successful flilelist generation.

**Pull request merged**
