### PR TITLE
Fix for tcl project script. Incdirs filenames contain \ that are interpreted as escape characters

### PR DESCRIPTION
**Pull request by phdussud**
Vivado tcl project scripts have a problem on Windows; The incdir names contain \ that are interpreted by tcl as escape characters. I am proposing to replace the \ by / in incdirs. Another solution would be to store the name as tcl literal strings like {incname}

### CODE REVIEW

**Comment by phdussud** [comment]
I am convinced that the right solution is to write the include pathnames as tcl literal strings like {incname}. 
I modifed my PR accordingly.

**Comment by olofk** [comment]
Thanks. That makes sense. I think changing \  to / is also a good way, and it turns out that most EDA tools even on Windows prefer /. But I think your solution also handles spaces in dir names which is an added bonus, so let's go with that.

Before accepting the patch though, we need to make sure it passes the regression tests. To pass the lint check, I recommend installing `pre-commit` which will automatically run the `black` formatter before every commit and properly reformat your changes. To pass the other tests, run `tox` from the Edalize repo root with the `GOLDEN_RUN` environment variable set. That will automatically update the reference files. Check that the changes look ok and then include them in the PR

**Comment by phdussud** [comment]
Thank you for the instructions. I run tox and I realized that this problem is a lot more complex than I originally thought. It works for the vivado tool chain because we only generate tcl files, but it does not work in general since the templates are not all tcl files. The literal string markers are different for every type of template. On top of this, it is possible to include a string in another string which makes the included string literal markers mis interpreted. 
I am not sure what to do at this point. I don't know if converting all of the \ to / will work for all of the template types that are currently in use. I am not sure that all EDA tools running on Windows are happy with a / pathname syntax. 
@olofk What do you think?

**Comment by phdussud** [comment]
I believe the right thing to do is to modify the templates instead of the data fed to the templates. I have modified the vivado project template which uses incdirs to format each include directory with a leading ' {' and a trailing '}'

**Comment by phdussud** [comment]
Here is the 4 changes that result from the change:
======================================================= FAILURES =======================================================
_____________________________________________________ test_vivado ______________________________________________________

make_edalize_test = <function make_edalize_test.<locals>._fun at 0x7f591d65fee0>

>   ???

P:\edalize\tests\test_vivado.py:12:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
P:\edalize\tests\edalize_common.py:90: in compare_files
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ref_dir = '/mnt/p/edalize/tests/test_vivado', work_root = '/tmp/pytest-of-phdussud/pytest-19/test_vivado0/0'
files = ['Makefile', 'test_vivado_0.tcl', 'test_vivado_0_synth.tcl', 'test_vivado_0_run.tcl', 'test_vivado_0_pgm.tcl']

>   ???
E   AssertionError: test_vivado_0.tcl
E   assert '# Auto-gener...!~ "*.bd"}]\n' == '# Auto-gener...!~ "*.bd"}]\n'
E     Skipping 875 identical leading characters in diff, use -v to show
E     - irs [list {.} {.}] [get_filesets sources_1]
E     ?           - ^^^ -
E     + irs [list . .] [get_filesets sources_1]
E     ?            ^
E       set_property top top_module [current_fileset]
E       set_property source_mgmt_mode None [current_project]...
E
E     ...Full output truncated (13 lines hidden), use '-vv' to show

P:\edalize\tests\edalize_common.py:139: AssertionError
_____________________________________________ test_vivado_minimal[params0] _____________________________________________

params = ('minimal', 'vivado'), tmpdir = local('/tmp/pytest-of-phdussud/pytest-19/test_vivado_minimal_params0_0')
make_edalize_test = <function make_edalize_test.<locals>._fun at 0x7f591d49f0d0>

>   ???

P:\edalize\tests\test_vivado.py:66:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ref_dir = '/mnt/p/edalize/tests/test_vivado/minimal'
work_root = '/tmp/pytest-of-phdussud/pytest-19/test_vivado_minimal_params0_0'
files = ['Makefile', 'test_vivado_minimal_0.tcl', 'test_vivado_minimal_0_run.tcl', 'test_vivado_minimal_0_pgm.tcl', 'test_vivado_minimal_0_synth.tcl']

>   ???
E   AssertionError: test_vivado_minimal_0.tcl
E   assert '# Auto-gener...es_1]\n\n\n\n' == '# Auto-gener...es_1]\n\n\n\n'
E     Skipping 162 identical leading characters in diff, use -v to show
E     - irs [list {.}] [get_filesets sources_1]
E     ?           - -
E     + irs [list .] [get_filesets sources_1]

P:\edalize\tests\edalize_common.py:139: AssertionError
_____________________________________________ test_vivado_minimal[params1] _____________________________________________

params = ('yosys', 'yosys'), tmpdir = local('/tmp/pytest-of-phdussud/pytest-19/test_vivado_minimal_params1_0')
make_edalize_test = <function make_edalize_test.<locals>._fun at 0x7f591d49f1f0>

>   ???

P:\edalize\tests\test_vivado.py:66:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ref_dir = '/mnt/p/edalize/tests/test_vivado/yosys'
work_root = '/tmp/pytest-of-phdussud/pytest-19/test_vivado_minimal_params1_0'
files = ['Makefile', 'test_vivado_yosys_0.tcl', 'test_vivado_yosys_0_run.tcl', 'test_vivado_yosys_0_pgm.tcl', 'edalize_yosys_procs.tcl', 'edalize_yosys_template.tcl']

>   ???
E   AssertionError: test_vivado_yosys_0.tcl
E   assert '# Auto-gener...7a35tcsg324-1' == '# Auto-gener...7a35tcsg324-1'
E     Skipping 196 identical leading characters in diff, use -v to show
E     - irs [list {.}] [get_filesets sources_1]
E     ?           - -
E     + irs [list .] [get_filesets sources_1]
E
E
E       ...
E
E     ...Full output truncated (2 lines hidden), use '-vv' to show

P:\edalize\tests\edalize_common.py:139: AssertionError
________________________________________________ test_vivado_board_file ________________________________________________

make_edalize_test = <function make_edalize_test.<locals>._fun at 0x7f591d49f790>

>   ???

P:\edalize\tests\test_vivado.py:89:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
P:\edalize\tests\edalize_common.py:90: in compare_files
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ref_dir = '/mnt/p/edalize/tests/test_vivado/board_file'
work_root = '/tmp/pytest-of-phdussud/pytest-19/test_vivado_board_file0/0'
files = ['Makefile', 'test_vivado_0.tcl', 'test_vivado_0_synth.tcl', 'test_vivado_0_run.tcl', 'test_vivado_0_pgm.tcl']

>   ???
E   AssertionError: test_vivado_0.tcl
E   assert '# Auto-gener...!~ "*.bd"}]\n' == '# Auto-gener...!~ "*.bd"}]\n'
E     Skipping 1120 identical leading characters in diff, use -v to show
E     - irs [list {.} {.}] [get_filesets sources_1]
E     ?           - ^^^ -
E     + irs [list . .] [get_filesets sources_1]
E     ?            ^
E       set_property top top_module [current_fileset]
E       set_property source_mgmt_mode None [current_project]...
E
E     ...Full output truncated (13 lines hidden), use '-vv' to show

P:\edalize\tests\edalize_common.py:139: AssertionError
=============================================== short test summary info ================================================
FAILED tests/test_vivado.py::test_vivado - AssertionError: test_vivado_0.tcl
FAILED tests/test_vivado.py::test_vivado_minimal[params0] - AssertionError: test_vivado_minimal_0.tcl
FAILED tests/test_vivado.py::test_vivado_minimal[params1] - AssertionError: test_vivado_yosys_0.tcl
FAILED tests/test_vivado.py::test_vivado_board_file - AssertionError: test_vivado_0.tcl
============================================ 4 failed, 107 passed in 25.65s ============================================

**Comment by olofk** [comment]
@phdussud I think that your first solution of just replacing \ with / is a better idea in that case, and there's even an easy way to do it. The `_add_include_dir` function (that you can find here https://github.com/olofk/edalize/blob/master/edalize/tools/vivado.py#L141) can take a third parameter to force the use of forward slashes. Try changing that line to `if not self._add_include_dir(f, incdirs, force_slash=True):` and see if that fixes your problem.

**Comment by phdussud** [comment]
Right, that was my first solution. I then got nervous about breaking some Linux pathname with embedded \ such as foo\ bar

**Comment by olofk** [comment]
It's good that you're careful about embedded backslashes and if you can make it work, that's good. But I think that realistically there are many other places in the code that will break if we have spaces or backslashes in the paths, so I'm fine with ignoring that problem

**Comment by phdussud** [comment]
Done. I am propagating the  change to the other tools (yosys, etc...) because I can't test them properly
Thanks!

**Comment by olofk** [comment]
Thank you for your contribution. Picked and pushed

**Pull request closed without merging**
