### PR TITLE
Common yosys module

### PR DESCRIPTION
**Pull request by kgugala**
This PR extracts Yosys wrapper from icestorm and trellis wrappers. Yosys is now defined as standalone edatool.

Also, yosys flow has been reimplemented to use tcl flow.

### CODE REVIEW

**Comment by mithro** [comment]
@kgugala / @olofk - Any idea how to deal with Yosys plugin support?

**Comment by kgugala** [comment]
> @kgugala / @olofk - Any idea how to deal with Yosys plugin support?

@mithro this can be done as a tool option to Yosys edatool wrapper. If this option will be set plugin loading will be injected to yosys tcl script. 

@olofk what do you think?

**Comment by olofk** [comment]
Thanks for this! It will simplify things a lot for the increasing numbers of backends that can use yosys.

I found one issue though. It looks like passing backend arguments on the command-line is broken. Tried it with serv by running `fusesoc run --tool=icestorm serv --pnr=none` and get `error: unrecognized arguments: --pnr=none` even though the pnr option is visible with `fusesoc run --tool=icestorm serv --help`. I guess it has to do with the options parsing. (As a side note, I'm planning to move the options parsing code from edalize to fusesoc at some point because I think it makes more sense to have it there)

**Comment by kgugala** [comment]
oh, I know what happens here. I pass all the provided args to subtool (yosys in this case). Yosys does not have `--pnr` option so it fails. I have to filter the opts before passing it further.

**Comment by kgugala** [comment]
I think the latest changes should fix the arguments issue. @olofk PTAL

**Comment by olofk** [comment]
This allows me to set the backend arguments, but it also allows any arguments to slip through. I would prefer to not allow this as it makes it harder to detect typos or invalid arguments that are specified on the command line.

I also notice that yosys is no longer called in quiet mode. It doesn't matter all that much, just mentioning it in case it was unintended. (As a side note, we should soon fix https://github.com/olofk/edalize/issues/21 so that it's possible to route output to files or an external tool using edalize)

**Comment by kgugala** [comment]
I have added a mechanism for checking the arg. Now the args are passed correctly and we can detect (and report) incorect params. @olofk PTAL one more time

**Comment by olofk** [comment]
Hi @kgugala 

I have finally had time to look at the code now. First of all, I took the liberty to massage these into four patches to make it easier for me to review. It's in the https://github.com/olofk/edalize/tree/cy branch. Could you please take a look there to see that I didn't mess anything up

I did some tests also and found an issue. It seems that string arguments passed through yosys with tcl needs to be wrapped in `{"value"}` . The current code just does `"value"` which makes yosys angry.

You can test it yourself with

    fusesoc library add fusesoc-cores https://github.com/fusesoc/fusesoc-cores
    fusesoc library add serv https://github.com/olofk/serv
    fusesoc run --target=tinyfpga_bx servant

I would also like to exchange the raised Exception with with RuntimeError, as FuseSoC catches those but not Exception.

I can change amend the patches here if that's easier for you

**Comment by olofk** [comment]
I have another update here. Seeing that the most effort was spent on battling the argument parsing, I decided to look at moving that part from Edalize into FuseSoC. I've been meaning to do that anyway but never prioritized it.

Turns out it was actually easier than I had expected. A bit more work needs to be done for runtime parameters, but the backends you have been working on only support compile-time parameters anyway.

The result of this is that I think we can simplify things on the Edalize side. This however requires some coordination, so I will push out a new release of FuseSoC first and then doing the plumbing in edalize

**Comment by kgugala** [comment]
HI @olofk the split you did seems to be OK. @piotr-binkowski found another issue with this PR - the templates were not installed. I have pushed his fix to this PR, please cherry-pick it to your branch.

I'll take a look at string arguments

**Comment by kgugala** [comment]
I have also fixed tcl quoting

**Comment by olofk** [comment]
ok, just a quick update. I am almost at the point where argument parsing is dropped from edalize. I want to get the argparse changes done first as this will drop some lines from your PR. Sorry for taking so long

**Comment by olofk** [comment]
Ok, it's done now. Many thanks for the patience. I will release a new Edalize version now and then we can look at the follow-up patches.

**Pull request closed without merging**
