### PR TITLE
Yosys -> Vivado flow support

### PR DESCRIPTION
**Pull request by kgugala**
This PR enables Vivado flow with Yosys synthesis. It is based on work done in #101, so #101 has to be merged first and than this PR should be rebased.

### CODE REVIEW

**Comment by olofk** [comment]
Are we ready to review this? Ideally I would like to see it rebased against master since there have been some bigger changes there

**Comment by kgugala** [comment]
@olofk let me rebase it first

**Comment by olofk** [comment]
Cool. Let me know when we're ready for a review

**Comment by kgugala** [comment]
this functionality has been merged in #151

**Pull request closed without merging**
