### PR TITLE
[GHDL] Dot notation for specifying my_lib.top_unit is supported

### PR DESCRIPTION
**Pull request by umarcor**
See ghdl/ghdl#1718, which was fixed a day after merging #231.

### CODE REVIEW

**Comment by imphil** [comment]
This PR removes the comment, but keeps the workaround added in #231 in place. Shouldn't we either keep the comment (in a modified form) for older versions of GHDL, or backout the whole change and only support newer GHDL versions?

**Comment by umarcor** [comment]
@imphil, looking at the codebase, it was not clear to me whether it is desirable to revert the workaround. Splitting the library and the primary unit is the recommended solution, and keeping it allows not having to detect the version of GHDL (it works with both older and newer versions). The dot notation feature is interesting when users have to manually write the CLI commands, because it saves time. However, when CLI commands are autogenerated (such as done by edalize), I don't think the dot notation adds any value.

**Comment by imphil** [comment]
I agree that it makes sense to keep this workaround for the time being. In that case, please don't remove the whole comment (since it explains what the code does). Instead, you can change it to something like "GHDL versions before XZY don't support ...".

**Comment by umarcor** [comment]
I rewrote the comment, instead of removing it.

**Review by imphil — APPROVED** [review]

**Comment by imphil** [comment]
Thanks, LGTM!

**Pull request merged**
