### PR TITLE
Correct tests for Python 3.5

### PR DESCRIPTION
**Pull request by GCHQDeveloper560**
#132

### CODE REVIEW

**Comment by GCHQDeveloper560** [comment]
I also removed Python 2.7 support and testing as discussed in #144.

**Comment by imphil** [comment]
Great! Can you please amend the Python2 commit with "Fixes #144" to keep a reference to this commit? Beyond that LGTM.

**Comment by imphil** [comment]
Thanks a lot!

**Comment by olofk** [comment]
Are we good now? Seems tests are passing at least

**Comment by imphil** [comment]
Yes, that one was ready.

**Pull request merged**
