### PR TITLE
Add modelsim option prerun_tcl

### PR DESCRIPTION
**Pull request by ttobsen**
This PR adds a new option for Modelsim which helps to execute Tcl scripts before simulation.

A very important use-cae is to disable the IEEE warnings. In Modelsim, this can either be done using the modelsim.ini or via Tcl commands. This Tcl commands have to be run right before simulation and not while compiling. This PR adds an option to specify a Tcl script which will be executed right before simulation starts.

### CODE REVIEW

**Comment by oholimoli** [comment]
I have the same problem. Hope this pull request will be accepted in the near future.

**Comment by ttobsen** [comment]
@olofk Can you have a look on this topic? I'm sorry for pressure. :disappointed:

**Comment by ttobsen** [comment]
This would be a way better solution!

I will check this out and give you feedback in a new PR. :-)

**Comment by olofk** [comment]
Don't forget to rerun and update the tests if you submit a PR :)

**Comment by ttobsen** [comment]
Closed due #354

**Pull request closed without merging**
