### PR TITLE
Add resource and timing reporting for several backends

### PR DESCRIPTION
**Pull request by GCHQDeveloper560**
#55

### CODE REVIEW

**Comment by GCHQDeveloper560** [comment]
I just tried running FuseSoC for the first time in a venv with this installed, and it looks like the naming convention I used broke Edalize's `get_edatool` in `__init__.py`. It's expecting classes to match `<module name>.capitalize()`. I used module names with underscores (`vivado_reporting.py`) and CapWords class names (`VivadoReporting`).

I'm not sure of the correct approach. These are likely `NON_TOOL_PACKAGES` so I could add them to that list. I could also change the class names to the expected format (e.g. `Vivado_reporting`) or change `get_edatool` to something more complex like
```python
def get_edatool(name):
    return getattr(
        import_module("{}.{}".format(__name__, name)),
        "".join(map(str.capitalize, name.split("_"))),
    )
```

Thoughts?

**Comment by GCHQDeveloper560** [comment]
I've gone ahead and added these as `NON_TOOL_PACKAGES` but can take a different approach if desired.

**Comment by olofk** [comment]
Thanks for this. It looks great. I hope to find some time soon to test it on a few of my own designs to see how it works. My main issue right now is that it adds quite a lot of new hard dependencies on other python packages. Could we instead just fail gracefully if e.g. the pandas packages aren't installed. I envision some corporate settings where it could be of importance to keep the number of edalize dependencies down.

**Comment by GCHQDeveloper560** [comment]
The quickest solution might be to add reporting as an "extra" feature through [`extras_require`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)? I don't have any experience with it, but it sounds like it would allow applications not using reporting to avoid the dependencies.

If that doesn't sounds appropriate I suspect PyParsing (already used in FuseSoC) might be required, but I could look into whether something could be done without NumPy/Pandas.

I'm certainly interested in feedback on how it works with your designs. I would be shocked if testing with more devices and tool versions didn't turn up bugs.

**Comment by olofk** [comment]
If you have identified numpy/pandas as a good solution, I definitely think we should stay with that. There is no written down policy for dependencies but I'm generally more fine with adding dependencies to FuseSoC than to Edalize, since Edalize is used within other projects to a higher degree. Ideally I would like to get rid of jinja2 as well, since that has caused about as much issues as it has saved time.

If extras_require is the way to go, please put it there (I have given up trying to understand the python packaging intricacies at this point and trust that other do the right thing). But I also think we could just do a try/except around the module imports and (optionally?) print out a note of warning if it couldn't be loaded. Then add some documentation and possibly some CLI command to let users know about the reporting infrastructure and how to install it if missing.

Come to think of it, I think the long-term solution would be something like an edalize namespace so that different backends can be developed more stand-alone and users can pick and choose the ones they want. But let's focus on getting this stuff in first. If you figure out how to make it optional, I will try to find time to run it on a couple of my designs to see how it holds up

**Comment by GCHQDeveloper560** [comment]
I won't claim to have any expertise in Python packaging either, but the latest commit should avoid installing the reporting dependencies unless Edalize is installed with the reporting option (`edalize[reporting]`). The reporting modules are still installed. There is currently no fallback functionality, so the modules check for their dependencies, log a (hopefully) useful error, and throw the import exception. It might make more sense to just not install the modules, but it's not clear to me how to do that.

**Comment by olofk** [comment]
I _finally_ got around to test it and it's crazy good :) Picked and pushed. Many thanks for taking the time to implement this

**Pull request closed without merging**
